# Generated by Django 4.0.3 on 2023-10-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algofun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteresource',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='algofun.note'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='algofun.source'),
        ),
        migrations.AlterField(
            model_name='problemresource',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='algofun.problem'),
        ),
        migrations.AlterField(
            model_name='submissionresource',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='algofun.submission'),
        ),
    ]
