# Generated by Django 4.0.3 on 2023-10-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algofun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_whiteboard_mode',
            field=models.BooleanField(default=False),
        ),
    ]
