# Generated by Django 4.0.3 on 2023-10-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algofun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='proficiency_level',
            field=models.CharField(choices=[('no_understanding', 'no understanding'), ('conceptual_understanding', 'conceptual understanding'), ('no_pass', 'no pass'), ('guided_pass', 'guided pass'), ('unsteady_pass', 'unsteady pass'), ('smooth_pass', 'smooth pass'), ('smooth_optimal_pass', 'smooth optimal pass')], default='no_understanding', max_length=100),
        ),
    ]
