# Generated by Django 4.0.3 on 2023-10-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algofun', '0002_alter_noteresource_note_alter_problem_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='similar_problems',
            field=models.ManyToManyField(blank=True, related_name='reverse_similar_problems', to='algofun.problem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='space_complexity_requirement',
            field=models.CharField(blank=True, choices=[('o1', 'o1'), ('nsqrt', 'nsqrt'), ('logn', 'logn'), ('n', 'n'), ('nlogn', 'nlogn'), ('n2', 'n2'), ('n3', 'n3'), ('2n', '2n'), ('nfactorial', 'nfactorial')], default='n', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_complexity_requirement',
            field=models.CharField(blank=True, choices=[('o1', 'o1'), ('nsqrt', 'nsqrt'), ('logn', 'logn'), ('n', 'n'), ('nlogn', 'nlogn'), ('n2', 'n2'), ('n3', 'n3'), ('2n', '2n'), ('nfactorial', 'nfactorial')], default='n', max_length=20, null=True),
        ),
    ]
