# Generated by Django 4.0.3 on 2023-10-10 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algofun', '0002_submission_is_whiteboard_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemnote',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='algofun.problem'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='algofun.problem'),
        ),
        migrations.AlterField(
            model_name='submissionnote',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='algofun.submission'),
        ),
    ]
