# Generated by Django 4.0.3 on 2023-12-02 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algofun', '0002_delete_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('resource_type', models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video'), ('article', 'article'), ('solution_post', 'solution post')], max_length=100)),
                ('note', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='algofun.note')),
            ],
        ),
    ]
