# Generated by Django 4.0.3 on 2023-12-02 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algofun', '0003_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='mentioned_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_mentioning_this_problem', to='algofun.problem'),
        ),
        migrations.AddField(
            model_name='note',
            name='mentioned_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_mentioning_this_submission', to='algofun.submission'),
        ),
    ]
