# Generated by Django 4.0.3 on 2023-10-13 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('algofun', '0003_alter_problemnote_problem_alter_submission_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
