# Generated by Django 4.0.3 on 2023-10-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algofun', '0004_problem_acceptance_rate_problem_asked_by_faang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='space_complexity',
            field=models.CharField(blank=True, choices=[('o1', 'o1'), ('nsqrt', 'nsqrt'), ('logn', 'logn'), ('n', 'n'), ('nlogn', 'nlogn'), ('n2', 'n2'), ('n3', 'n3'), ('2n', '2n'), ('nfactorial', 'nfactorial')], default='n', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_complexity',
            field=models.CharField(blank=True, choices=[('o1', 'o1'), ('nsqrt', 'nsqrt'), ('logn', 'logn'), ('n', 'n'), ('nlogn', 'nlogn'), ('n2', 'n2'), ('n3', 'n3'), ('2n', '2n'), ('nfactorial', 'nfactorial')], default='n', max_length=20),
        ),
    ]
