# Generated by Django 4.0.3 on 2023-12-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algofun', '0004_problem_acceptance_rate_problem_asked_by_faang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_review',
            field=models.BooleanField(default=False),
        ),
    ]
