# Generated by Django 4.0.3 on 2023-10-13 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algofun', '0004_note_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='duration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
