# Generated by Django 4.0.3 on 2023-12-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algofun', '0005_tag_created_at_tag_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink'), ('grey', 'Grey')], default='GRAY', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='proficiency_level',
            field=models.CharField(choices=[('no_understanding', 'no understanding'), ('conceptual_understanding', 'conceptual understanding'), ('no_pass', 'no pass'), ('guided_pass', 'guided pass'), ('unsteady_pass', 'unsteady pass'), ('smooth_pass', 'smooth pass'), ('smooth_optimal_pass', 'smooth optimal pass')], max_length=30),
        ),
    ]
