# Generated by Django 4.0.3 on 2023-12-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algofun', '0006_note_note_type_alter_submission_proficiency_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink'), ('gray', 'Gray')], default='gray', max_length=30),
        ),
    ]
